trigger:
- master

pr:
- master

stages:

- stage: build

  jobs:

  - job: build

    pool:
      vmImage: ubuntu-latest

    steps:

    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerComposeFile: 'docker-compose.prod.yml'
        action: 'Build services'
      displayName: docker-compose build

  - job: test

    pool:
      vmImage: ubuntu-latest

    variables:
      sdkVersion: 3.1.x
      solutionPath: .
      buildConfiguration: Release

    steps:

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '2.1.x'
      displayName: dotnet 2.1.x

    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'CALM API'
        organization: '2002-feb24-net'
        scannerMode: 'MSBuild'
        projectKey: '2002-feb24-net_CALM-API'
        projectName: 'CALM-api'
        extraProperties: 'sonar.cs.opencover.reportsPaths=$(Common.TestResultsDirectory)/*/coverage.opencover.xml'
      displayName: sonarcloud analysis prepare

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '$(sdkVersion)'
      displayName: dotnet $(sdkVersion)

    - script: dotnet build
        --configuration $(buildConfiguration)
      workingDirectory: $(solutionPath)
      displayName: dotnet build

    - script: dotnet test
        --configuration $(buildConfiguration)
        --logger trx
        --no-build
        --results-directory $(Common.TestResultsDirectory)
        --settings coverlet.runsettings
      workingDirectory: $(solutionPath)
      continueOnError: true
      displayName: dotnet test

    - task: SonarCloudAnalyze@1
      displayName: sonarcloud analysis run

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '$(Common.TestResultsDirectory)/*.trx'
      displayName: test results build publish

    - task: PublishCodeCoverageResults@1
      condition: succeededOrFailed()
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: $(Common.TestResultsDirectory)/*/coverage.cobertura.xml
      displayName: code coverage build publish

    - task: SonarCloudPublish@1
      condition: succeededOrFailed()
      inputs:
        pollingTimeoutSec: '300'
      displayName: sonarcloud results build publish

- stage: deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn: build

  jobs:

  # - deployment: deploy_dev

  - job: push

    pool:
      vmImage: ubuntu-latest

    # environment: dev

    # strategy:
    #   runOnce:
    #     deploy:

    steps:

          # - checkout: self

          # - download: none

    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerComposeFile: 'docker-compose.prod.yml'
        action: 'Build services'
      displayName: docker-compose build

    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'CalmApi'
        dockerComposeFile: 'docker-compose.prod.yml'
        action: 'Push services'
      displayName: docker-compose push

          # - task: AzureWebAppContainer@1
          #   inputs:
          #     azureSubscription: 'Azure subscription 1(34c1f765-2be7-443c-b6cc-1dfb59828d08)'
          #     appName: 'calm-api'
          #     multicontainerConfigFile: 'docker-compose.prod.yml'
          #   displayName: azure app service deploy


    - task: PublishPipelineArtifact@1
      displayName: k8s manifest publish
      inputs:
        targetPath: 'k8s'
        artifact: 'k8s'
        publishLocation: 'pipeline'

  - deployment: deploy_dev
    dependsOn: push

    pool:
      vmImage: ubuntu-latest

    environment: dev

    strategy:
      runOnce:
        deploy:
          steps:

          - task: KubernetesManifest@0
            displayName: kubectl apply
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'dev-default-1588890708309'
              namespace: 'default'
              manifests: '$(Pipeline.Workspace)/k8s/**/*.yml'

          - task: Kubernetes@1
            displayName: kubectl rollout restart
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'dev-default-1588890708309'
              namespace: 'default'
              command: 'rollout'
              useConfigurationFile: true
              configuration: '$(Pipeline.Workspace)/k8s/deployment'
              arguments: 'restart'
              secretType: 'dockerRegistry'
              containerRegistryType: 'Azure Container Registry'
              