version: '3.7'

services:

  web:
    build: 
      context: .
      dockerfile: api.Dockerfile
    image: brendanngoran/calmapi:1.0

  data:
    build: 
      context: .
      dockerfile: db.Dockerfile
    image: brendanngoran/calmdb:1.0
    # environment:
    #   POSTGRES_USER: "postgres"
    #   POSTGRES_PASSWORD: "Password123"
    #   POSTGRES_DB: "calmdb"
