version: '3.7'

services:

  web:
    build: CalmService
    image: brendanngoran/calmapi:1.0
    depends_on:
      - data
    ports:
      - 80:80
    networks:
      - default
    environment:
      DatabaseConnection: CalmDbPostgreSqlDockerCompose
      ConnectionStrings__CalmDbPostgreSqlDockerCompose: Host=data;Database=CalmDb;Username=postgres;Password=Pass@word
      EnsureDatabaseCreated: 'true'
      CorsOrigins__0: http://localhost:4200
      CorsOrigins__1: https://calm-api.azurewebsites.net
      UseHttpsRedirection: 'false'

  data:
    image: postgres:12.0
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: Pass@word

networks:
  default: