apiVersion: apps/v1
kind: Deployment
metadata:
  name: calm-db
  labels:
    app: calm
    role: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calm
      role: db
  template:
    metadata:
      labels:
        app: calm
        role: db
    spec:
      containers:
      - name: calm-db
        image: brendanngoran/calmdb:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5432